logging:
  level:
    com.example.demo: DEBUG
  r2dbc:
    url: 'r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=TRUE'
    pool:
      maxIdleTime: 30m
      initialSize: 10
      maxSize: 10
      validationQuery: select 1

server:
  port: 8080
spring:
  codec:
    max-in-memory-size: 1MB
debug: false

